mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from . import views
from django.urls import path

app_name = 'polls'

urlpatterns = [
    path('main', views.index, name='index'),
    path('<int:question_id>', views.detail, name='detail'),
    path('<int:question_id>/vote', views.vote, name='vote'),
    path('<int:question_id>/results', views.results, name='results')
]

polls/models.py
from django.db import models

# Create your models here.

# 1. Pytanie:
# - treść
# - data publikacji


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(verbose_name='Date published')

    def __str__(self):
        return f'"{self.question_text}"'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'"{self.choice_text}"'

polls/views.py
# kolejnosc zachowywania importow tak jak poniezej, dodatkowo alfabetycznie sortujemy

# importy z modolow systemow np import random

# importy z dodatkami ktore instalujemy
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.datastructures import MultiValueDictKeyError

# importy zwiazane z aplikacja
from .models import Question, Choice

from django.http import HttpResponse

# request- pod ta zmienna kryje sie obiekt requestu, który zapisuje informacje z zadaniem uzytkowinika,
# czyli wtedy kiedy uzytkownik wchodzi w dany url

# 1. widok wszystkich opublikowanych pytan


def index(request):
    questions = Question.objects.all()
    title = 'Lista wszystkich pytan'
    context = {
        'questions': questions,
        'title': title,
    }

    # {} - kontekst, nazwa zwiazana z django
    # render- renderuje, uruchamia wszystkie zmienne itd. tak abysmy np. zamiast petli mileli n powtorzen czegos itd.

    return render(request, 'polls/index.html', context)

# 2. Wdiok szczegolowy danego pytania


def detail(request, question_id):

    #question = Question.objects.get(id=question_id)
    question = get_object_or_404(Question, id=question_id)
    title = f'Pytanie: {question.question_text}'

    context = {
        'question': question,
        'title': title,
    }

    return render(request, 'polls/detail.html', context)


def vote(request, question_id):

    question = get_object_or_404(Question, id=question_id)

    # jezeli jest pierwsza metoda to nie trzeba ifa
    # if request.method=='POST':

    # Pierwszy sposob, szybszy
    choice_form = request.POST.get('choice')

    # Drugi sposob dluzszy
    # sprawdzenie czy jest w inputcie name choice w (detail.html), jezeli nie to
    # przekierowuje na strone z detail zamiast do vote
    # try:
    #     # choice nazwa z name z detial.html w inputcie
    #     choice_form = request.POST['choice']
    # except MultiValueDictKeyError:
    #     return redirect('polls:detail', question_id)

    try:
        # wybieramy choice, ktore ma dane id z danego question
        selected_choice = question.choice_set.get(id=choice_form)
    except Choice.DoesNotExist:
        return redirect('polls:detail', question_id)

    selected_choice.votes += 1
    selected_choice.save()

    return redirect('polls:results', question_id)
    # jezeli jest pierwsza metoda to tego nie trzeba
    # else:
    #     return redirect('polls:detail', question_id)


def results(request, question_id):

    question = get_object_or_404(Question, id=question_id)
    title = f'Wyniki: {question.question_text}'

    context = {
        'question': question,
        'title': title,
    }

    return render(request, 'polls/results.html', context)

# 3. widok, który reaguje na zaglosowanie przez uzytkownika (usera)
# 4. widok z wynikiami dla danego pytania

polls/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Ankiety &bull; {{ title }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css'%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>

<body>



    <ul class="nav nav-pills">

        <a href="{% url 'polls:index' %}"><img
                src="https://pbs.twimg.com/profile_images/1168557866271334401/iX9TQtl8_400x400.jpg" alt=""></a>

        <li class="nav-item">
            <a class="nav-link" href="http://127.0.0.1:8000/polls/1">Pytanie 1</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="http://127.0.0.1:8000/polls/2">Pytanie 2</a>
        </li>

    </ul>

    <div class="container-fluid">
        <img src="https://ak.picdn.net/shutterstock/videos/1010260439/thumb/11.jpg" alt="">
        <div class="textbox">
            <div class="top">
                <h1>{{ title }}</h1>
            </div>
            <div class="bottom">
                <main>{% block content %}{% endblock %}</main>
            </div>
        </div>

    </div>




    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    </script>
</body>

</html>

polls/templates/polls/detail.html
{% extends "base.html" %}
{% block content %}

<section class="container">
    <p>Możliwe odpowiedzi: </p>

    <form method="POST" action="{% url 'polls:vote' question.id %}">
        {% csrf_token %}
        <ul>
            {% for choice in question.choice_set.all %}
            <li>
                <label>
                    <input type="radio" name="choice" value="{{ choice.id }}" required> {{ choice.choice_text }}
                </label>
            </li>
            {% endfor %}
        </ul>
        <input type="submit" value="Głosuj">
    </form>
</section>

{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}
{% block content %}
{% for question in questions %}
<section>
    <h3><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></h3>
</section>
{% endfor %}
{% endblock %}

polls/templates/polls/results.html
{% extends "base.html" %}
{% block content %}

<section>
    <p>Możliwe odpowiedzi: </p>
    <ul>
    {% for choice in question.choice_set.all %}
        <li><b>{{ choice.choice_text }}</b>, głosów: {{ choice.votes }}</li>
    {% endfor %}
    </ul>
</section>

{% endblock %}